services:
  postgres:
    image: postgres:16-alpine
    container_name: ronda-db
    restart: always
    environment:
      POSTGRES_USER: ronda_user
      POSTGRES_PASSWORD: ronda_password
      POSTGRES_DB: ronda_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ronda_user -d ronda_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
